[build]
  publish = "dist"
  command = "npm run build"

# Handle client-side routing for React app
[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/debug"
  to = "/index.html"
  status = 200

# Catch-all redirect for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
