[build]
  publish = "client/dist"
  command = "cd client && pnpm build"

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
